(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
(function(){var e;e={structures:require("../structures/structures"),spawns:require("../spawns/spawns"),creeps:require("../creeps/creeps"),roles:require("../roles/roles")},module.exports=e}).call(this);
},{"../creeps/creeps":2,"../roles/roles":6,"../spawns/spawns":8,"../structures/structures":9}],2:[function(require,module,exports){
(function(){var e,t;e={spawns:require("../spawns/spawns")},t={run:function(){},type:{harvester:{counter:0,level:[[MOVE,CARRY,WORK],[MOVE,MOVE,CARRY,WORK]]},upgrader:{counter:0,level:[[MOVE,CARRY,WORK],[MOVE,MOVE,CARRY,WORK]]},healer:{counter:0,level:[[HEAL,MOVE,CARRY]]}},cost:function(e){var t,r;return t={move:50,carry:50,work:20,heal:200,tough:20,attack:80,ranged_attack:150},r=0,_.forEach(e,function(e){return r+=t[e]}),r},create:function(t,r){var n;if(r||(r=0),console.log("Attempt to create a "+t+" level "+r+". Body: "+this.type[t].level[r]+". Cost: "+this.cost(this.type[t].level[r])+". Counter: "+this.type[t].counter),n=e.spawns.getEnergyAbove(this.cost(this.type[t].level[r]))[0])return n.createCreep(this.type[t].level[r],t+"_"+this.type[t].counter,{role:t}),this.type[t].counter+=1},autoSpawn:function(){return this.create("upgrader")}},module.exports=t}).call(this);

},{"../spawns/spawns":8}],3:[function(require,module,exports){
(function(){var r,e;r=require("./core/core"),(e=function(){var e,a,s,u=[];r.creeps.autoSpawn(),e=0;for(a in Game.creeps)switch(s=Game.creeps[a],s.memory.role){case"harvester":u.push(r.roles.harvester.run(s));break;case"upgrader":u.push(r.roles.upgrader.run(s));break;case"builder":u.push(r.roles.builder.run(s))}return u})()}).call(this);
},{"./core/core":1}],4:[function(require,module,exports){
(function(){var r;r={run:function(r){var e,i;if(r.memory.building&&0===r.carry.energy&&(r.memory=!1),r.memory.building||r.carry.energy!==r.carryCapacity||(r.memory.building=!0),r.memory.building){if(e=r.room.find(FIND_CONSTRUCTION_SITES),e.length&&r.build(e[0])===ERR_NOT_IN_RANGE)return r.moveTo(e[0])}else if(i=creeps.rooms.find(FIND_SOURCES),r.harvest(i[0]===ERR_NOT_IN_RANGE))return r.moveTo(i[0])}},module.exports=r}).call(this);
},{}],5:[function(require,module,exports){
(function(){var r;r={run:function(r){var e,t;if(r.carry.energy<r.carryCapacity){if(e=r.room.find(FIND_SOURCES),r.harvest(e[0])===ERR_NOT_IN_RANGE)return r.moveTo(e[0])}else if(t=r.room.find(FIND_STRUCTURES,{filter:function(r){return(r.structureType===STRUCTURE_EXTENSION||r.structureType===STRUCTURE_SPAWN)&&r.energy<r.energyCapacity}}),t.length>0&&r.transfer(t[0],RESOURCE_ENERGY)===ERR_NOT_IN_RANGE)return r.moveTo(t[0])}},module.exports=r}).call(this);

},{}],6:[function(require,module,exports){
(function(){var r;r={builder:require("./builder/builder"),harvester:require("./harvester/harvester"),upgrader:require("./upgrader/upgrader")},module.exports=r}).call(this);

},{"./builder/builder":4,"./harvester/harvester":5,"./upgrader/upgrader":7}],7:[function(require,module,exports){
(function(){var r;r={run:function(r){var o;if(r.memory.upgrading&&0===r.carry.energy&&(r.memory.upgrading=!1),r.memory.upgrading||r.carry.energy!==r.carryCapacity||(r.memory.upgrading=!0),r.memory.upgrading){if(r.upgradeController(r.room.controller)===ERR_NOT_IN_RANGE)return r.moveTo(r.room.controller)}else if(o=r.room.find(FIND_SOURCES),r.harvest(o[0])===ERR_NOT_IN_RANGE)return r.moveTo(o[0])}},module.exports=r}).call(this);

},{}],8:[function(require,module,exports){
(function(){var e,t;e={structures:require("../structures/structures")},t={getAll:function(t){return e.structures.getAll([STRUCTURE_SPAWN])},getEnergyless:function(){var e,t;return e=this.getAll(),t=_.filter(e,function(e){return e.energy<e.energyCapacity})},getEnergyAbove:function(e){var t,r;return t=this.getAll(),r=_.filter(t,function(t){return t.energy>e})},getEnergyBelow:function(e){var t,r;return t=this.getAll(),r=_.filter(t,function(t){return t.energy<e})}},module.exports=t}).call(this);

},{"../structures/structures":9}],9:[function(require,module,exports){
(function(){function r(r,e,t){function n(r,e,c){var l,a,f,s,b,g,h,p;if(null==r||null==e)return r===e;if(r.__placeholder__||e.__placeholder__)return!0;if(r===e)return 0!==r||1/r==1/e;if(l=o.call(r),o.call(e)!=l)return!1;switch(l){case"[object String]":return r==String(e);case"[object Number]":return r!=+r?e!=+e:0==r?1/r==1/e:r==+e;case"[object Date]":case"[object Boolean]":return+r==+e;case"[object RegExp]":return r.source==e.source&&r.global==e.global&&r.multiline==e.multiline&&r.ignoreCase==e.ignoreCase}if("object"!=typeof r||"object"!=typeof e)return!1;for(a=c.length;a--;)if(c[a]==r)return!0;if(c.push(r),f=0,s=!0,"[object Array]"==l){if(b=r.length,g=e.length,i){switch(t){case"===":s=b===g;break;case"<==":s=b<=g;break;case"<<=":s=b<g}f=b,i=!1}else s=b===g,f=b;if(s)for(;f--&&(s=f in r==f in e&&n(r[f],e[f],c)););}else{if("constructor"in r!="constructor"in e||r.constructor!=e.constructor)return!1;for(h in r)if(u(r,h)&&(f++,!(s=u(e,h)&&n(r[h],e[h],c))))break;if(s){p=0;for(h in e)u(e,h)&&++p;i?s="<<="===t?f<p:"<=="===t?f<=p:f===p:(i=!1,s=f===p)}}return c.pop(),s}var o={}.toString,c={}.hasOwnProperty,u=function(r,e){return c.call(r,e)},i=!0;return n(r,e,[])}var e;e={getAll:function(e){var t,n;return t=[STRUCTURE_SPAWN],null!=e&&(t=e),n=Game.structures,n=_.filter(n,function(e){var n;return n=0,_.forEach(t,function(r,t){if(e.structureType===r)return++n}),r(n,t.length,"===")})}},module.exports=e}).call(this);
},{}]},{},[3]);
